//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShanghaiTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShanghaiTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 《血战上海滩》八项属性修改器
        ///——————————————————
        ///52pojie@烟99
        ///
        ///本修改器可以实现弹药锁定、追加积分和杀敌、清空误伤平民等功能，还可以实现窗口模式运行游戏，并额外追加了INI文件加解密和PCK打包解包功能，以满足不同人的需要。
        ///
        ///【作弊功能一览】
        ///功能1：解锁所有武器
        ///功能2：拥有马克沁重机枪
        ///功能3：弹药锁定
        ///功能4：追加九条命
        ///功能5：追加1000杀敌得分
        ///功能6：追加100杀敌数
        ///功能7：清空误伤平民
        ///功能8：解锁所有关卡
        ///
        ///【注意事项】
        ///1、弹夹和马克沁锁定后，若重开新局则须先解锁再锁定才能生效！
        ///2、窗口模式和使用解包的PCK运行游戏是给有需要的同学使用的，打包PCK时要仔细阅读随选项卡弹出的提示框，操作不当可能会造成游戏崩溃。
        ///3、修改INI的时候注意分清是加密的文件还是解密的文件，以防弄混造成游戏崩溃，后续有时间将有优化此功能。
        ///4、再次重申，PCK打包解包功能仅限技术研究使用，严禁将所提取到的和修改过的资源文件用于其他用途，否则修改器作者概不承担因而造成的一切后果。 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox_52pojieLogo_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox_52pojieLogo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox_Cover_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox_Cover.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound1 {
            get {
                object obj = ResourceManager.GetObject("Sound1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound2 {
            get {
                object obj = ResourceManager.GetObject("Sound2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound3 {
            get {
                object obj = ResourceManager.GetObject("Sound3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
