//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShanghaiTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShanghaiTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 《血战上海滩》九项属性修改器
        ///——————————————————
        ///52pojie@烟99
        ///
        ///本修改器可以实现弹药锁定、追加积分和杀敌、清空误伤平民等功能，还可以实现窗口模式运行游戏，并额外追加了INI文件加解密和PCK打包解包功能，以满足不同人的需要。
        ///
        ///【作弊功能一览】
        ///功能1：解锁所有武器
        ///功能2：拥有马克沁重机枪
        ///功能3：永远不用换弹夹
        ///功能4：突破连发射击限制
        ///功能5：追加九条命
        ///功能6：追加1000杀敌得分
        ///功能7：追加100杀敌数
        ///功能8：清空误伤平民
        ///功能9：解锁所有关卡
        ///
        ///【更新日志】
        ///--------------------------------------------
        ///2026.10.01 -- v1.0.2
        ///--------------------------------------------
        ///1、优化&lt;永远不用换弹夹&gt;修改项的实现方式。
        ///2、新增&lt;突破连发射击限制&gt;修改项，它能让手枪、步枪和巴祖卡这样的单发武器像冲锋枪一样能够连发（手榴弹暂不支持）。推荐搭配&lt;永远不用换弹夹&gt;修改项使用，可以做到终极必杀。
        ///
        ///------------ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox_52pojieLogo_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox_52pojieLogo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox_Cover_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox_Cover.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound1 {
            get {
                object obj = ResourceManager.GetObject("Sound1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound2 {
            get {
                object obj = ResourceManager.GetObject("Sound2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Sound3 {
            get {
                object obj = ResourceManager.GetObject("Sound3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
